In [20]:
import torch as tc
import torch.nn as nn

class FFN(nn.Module):
  def __init__(self, inp, hidden, ops):
    super().__init__()
    self.lin1 = nn.Linear(inp, hidden)
    self.sig = nn.Sigmoid()
    self.lin2 = nn.Linear(hidden, ops)
  def forward(self, x):
    x = self.lin1(x)
    x = self.sig(x)
    x = self.lin2(x)
    return x

input_size = 2
hidden_size = 1
output_size = 1

model = FFN(input_size, hidden_size, output_size)

data = tc.randn(20, input_size)
# print(data)
datax=tc.tensor([[1., 1.], [1., -1], [-1., 1.], [-1, -1]])
datay = tc.tensor([-1., 1., 1., -1.])

# Without Back Propagation

In [21]:
for i in datax:
  print(model(i))

tensor([-1.2612], grad_fn=<AddBackward0>)
tensor([-1.4598], grad_fn=<AddBackward0>)
tensor([-1.0180], grad_fn=<AddBackward0>)
tensor([-1.1977], grad_fn=<AddBackward0>)


## With training

In [22]:
epochs = 1000
mseloss = nn.MSELoss()
optimizer = tc.optim.Adam(model.parameters(), lr = 0.03)

for epoch in range(epochs):
  for i in range(4):

    optimizer.zero_grad()

    yhat = model(datax[i])

    loss = mseloss(yhat, datay[i])

    loss.backward()

    optimizer.step()

    if epoch%100==0:
      print(f"loss = {loss}")

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


loss = 0.06820685416460037
loss = 5.774493217468262
loss = 3.806204080581665
loss = 0.006786513142287731
loss = 1.0057238340377808
loss = 1.003869652748108
loss = 0.9983976483345032
loss = 1.007826566696167
loss = 1.0065325498580933
loss = 1.0000817775726318
loss = 1.003781795501709
loss = 1.004949927330017
loss = 0.8933963179588318
loss = 0.3094491958618164
loss = 1.2683459520339966
loss = 0.8830332159996033
loss = 0.4592752456665039
loss = 0.00035920587833970785
loss = 1.7820621728897095
loss = 0.45855069160461426
loss = 0.4513002038002014
loss = 5.3857431339565665e-05
loss = 1.784401535987854
loss = 0.4506608843803406
loss = 0.44913750886917114
loss = 1.677454201853834e-05
loss = 1.7844961881637573
loss = 0.44849222898483276
loss = 0.4481489956378937
loss = 6.868365289847134e-06
loss = 1.7844678163528442
loss = 0.44749483466148376
loss = 0.4475972354412079
loss = 3.251384896429954e-06
loss = 1.7844254970550537
loss = 0.44693616032600403
loss = 0.4472527801990509
loss = 1.68359326835

In [23]:
for i in datax:
  print(model(i))

tensor([-0.3314], grad_fn=<AddBackward0>)
tensor([1.0011], grad_fn=<AddBackward0>)
tensor([-0.3320], grad_fn=<AddBackward0>)
tensor([-0.3314], grad_fn=<AddBackward0>)
