In [ ]:
import torch as tc
import torch.nn as nn
import numpy as np
import torch

In [ ]:
class MP_Neuron(nn.Module):
  def __init__(self, ):
    super().__init__()
    self.weights=tc.tensor([1, -1])
    self.bias = 0
    self.threshold = 1

  def forward(self, x):
    net = tc.sum((self.weights*x)) + self.bias
    return tc.where(net>=self.threshold, tc.tensor(1.0), tc.tensor(0.0))
data=[
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]

mp = MP_Neuron()

for j in tc.tensor(data):
  print(j,mp(j))

tensor([0, 0]) tensor(0.)
tensor([0, 1]) tensor(0.)
tensor([1, 0]) tensor(1.)
tensor([1, 1]) tensor(0.)


In [ ]:
class XOR_N(nn.Module):
  def __init__(self, ):
    super().__init__()
    self.lin1 = nn.Linear(2, 2)
    self.sig = nn.Sigmoid()
    self.lin2 = nn.Linear(2, 1)
  def forward(self, x):
    x = self.lin1(x)
    x = self.sig(x)
    x = self.lin2(x)
    return x
model = XOR_N()
epochs = 1000
mseloss = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.03)

In [ ]:
data2=[0,1,1,0]
x = tc.tensor([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0]
])

y = tc.tensor([0.0,1.0,1.0,0.0]).view(-1,1)

In [ ]:
epochs = 1000

for epoch in range(epochs):
  for i in range(4):

    optimizer.zero_grad()

    yout = model(x[i])

    loss = mseloss(yout, y[i])

    loss.backward()

    optimizer.step()

    if epoch%100==0:
      print(f"loss = {loss}")

loss = 1.0746958878371515e-13
loss = 1.7408297026122455e-13
loss = 2.2737367544323206e-13
loss = 1.2789769243681803e-13
loss = 5.863365348801608e-14
loss = 8.881784197001252e-14
loss = 5.684341886080802e-14
loss = 7.599476603559197e-14
loss = 2.936539900133539e-14
loss = 3.197442310920451e-14
loss = 3.197442310920451e-14
loss = 2.8102520310824275e-14
loss = 3.197442310920451e-14
loss = 3.197442310920451e-14
loss = 3.197442310920451e-14
loss = 3.197442310920451e-14
loss = 1.0116907311896739e-14
loss = 1.4210854715202004e-14
loss = 1.4210854715202004e-14
loss = 1.700029006457271e-14
loss = 1.0116907311896739e-14
loss = 1.4210854715202004e-14
loss = 1.4210854715202004e-14
loss = 1.7985612998927536e-14
loss = 1.3336554083309693e-14
loss = 3.197442310920451e-14
loss = 5.684341886080802e-14
loss = 2.7200464103316335e-15
loss = 5.551115123125783e-17
loss = 0.0
loss = 0.0
loss = 5.551115123125783e-17
loss = 5.551115123125783e-17
loss = 0.0
loss = 0.0
loss = 5.551115123125783e-17
loss = 5.55111

In [ ]:
print("{:.10f}".format(float(model(tc.tensor([0.0,1.0]))[0].detach().numpy())))
# print("{:.10f}".format(1.0e-05))
# float(tc.tensor(0).numpy())

0.9999997020
