In [ ]:
import torch as tc
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a = [
    list("++++"),
    list("+   "),
    list("++++"),
    list("   +"),
    list("++++")
]

b = [
    list("++++"),
    list("+   "),
    list("+   "),
    list("+   "),
    list("++++")
]

a = np.array(a)
a = tc.tensor(np.where(a == "+", 1, -1), dtype=tc.float32)

b = np.array(b)
b = tc.tensor(np.where(b == "+", 1, -1), dtype=tc.float32)

t1 = tc.tensor(1.0)
t2 = tc.tensor(0.0)
print(a)
print(b)

tensor([[ 1.,  1.,  1.,  1.],
        [ 1., -1., -1., -1.],
        [ 1.,  1.,  1.,  1.],
        [-1., -1., -1.,  1.],
        [ 1.,  1.,  1.,  1.]])
tensor([[ 1.,  1.,  1.,  1.],
        [ 1., -1., -1., -1.],
        [ 1., -1., -1., -1.],
        [ 1., -1., -1., -1.],
        [ 1.,  1.,  1.,  1.]])


In [ ]:
print(a.flatten())
print(b.flatten())

tensor([ 1.,  1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1., -1., -1.,
        -1.,  1.,  1.,  1.,  1.,  1.])
tensor([ 1.,  1.,  1.,  1.,  1., -1., -1., -1.,  1., -1., -1., -1.,  1., -1.,
        -1., -1.,  1.,  1.,  1.,  1.])


In [ ]:
class HebbsRule(nn.Module):
  def __init__(self, arr_size=(3, 3)):
    super().__init__()
    self.len = np.prod(arr_size)
    self.weights = tc.zeros(self.len)
    self.bias = tc.zeros(1)

  def forward(self, data, target):
    self.weights.data += data*target
    self.bias.data += target

    return (data*self.weights)
model = HebbsRule(arr_size=a.shape)

model(a.flatten(), 1)
model(b.flatten(), -1)

model.weights, model.bias

(tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.,  2., -2.,  0.,
          0.,  2.,  0.,  0.,  0.,  0.]),
 tensor([0.]))