In [1]:
import torch as tc
import torch.nn as nn
import numpy as np
import torch

In [2]:
class MP_Neuron(nn.Module):
  def __init__(self, ):
    super().__init__()
    self.weights=tc.tensor([1, -1])
    self.bias = 0
    self.threshold = 1

  def forward(self, x):
    net_input = tc.sum((self.weights*x)) + self.bias
    return tc.where(net_input>=self.threshold, tc.tensor(1.0), tc.tensor(0.0))

In [3]:
data=[
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]

mp = MP_Neuron()

for i in tc.tensor(data):
  print(i,mp(i))

tensor([0, 0]) tensor(0.)
tensor([0, 1]) tensor(0.)
tensor([1, 0]) tensor(1.)
tensor([1, 1]) tensor(0.)


In [4]:
class XOR_N(nn.Module):
  def __init__(self, ):
    super().__init__()
    self.lin1 = nn.Linear(2, 2)
    self.sig = nn.Sigmoid()
    self.lin2 = nn.Linear(2, 1)
  def forward(self, x):
    x = self.lin1(x)
    x = self.sig(x)
    x = self.lin2(x)
    return x

In [5]:
model = XOR_N()

In [6]:
epochs = 1000
mseloss = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.03)

In [7]:
data2=[0,1,1,0]

In [8]:
X = tc.tensor([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0]
])

Y = tc.tensor([0.0,1.0,1.0,0.0]).view(-1,1)

In [9]:
epochs = 1000

for epoch in range(epochs):
  for i in range(4):

    optimizer.zero_grad()

    yhat = model(X[i])

    loss = mseloss(yhat, Y[i])

    loss.backward()

    optimizer.step()

    if epoch%100==0:
      print(f"loss = {loss}")

loss = 0.32120999693870544
loss = 2.210040330886841
loss = 2.1302859783172607
loss = 0.14566670358181
loss = 0.2279445379972458
loss = 0.2839958667755127
loss = 0.2149418592453003
loss = 0.2627183794975281
loss = 0.00044535021879710257
loss = 0.2466716170310974
loss = 0.0030595664866268635
loss = 0.2874130308628082
loss = 2.608738941489719e-05
loss = 0.2522244155406952
loss = 0.00017181693692691624
loss = 0.2604823708534241
loss = 6.289687917160336e-06
loss = 0.2522731125354767
loss = 4.188050297670998e-05
loss = 0.2562997043132782
loss = 2.2932420051802183e-06
loss = 0.25225940346717834
loss = 1.5500016161240637e-05
loss = 0.25470802187919617
loss = 1.0206432534687337e-06
loss = 0.25225141644477844
loss = 6.999892320891377e-06
loss = 0.25390005111694336
loss = 5.107810920890188e-07
loss = 0.2522471249103546
loss = 3.5500679587130435e-06
loss = 0.25342437624931335
loss = 2.7599821805779357e-07
loss = 0.2522442936897278
loss = 1.941169557539979e-06
loss = 0.2531172037124634
loss = 1.573

In [10]:
print("{:.10f}".format(float(model(tc.tensor([0.0,1.0]))[0].detach().numpy())))


0.4998581111
